# Generated by Django 4.0.2 on 2022-06-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombre', models.CharField(max_length=80, verbose_name='NombreProducto')),
                ('precio', models.CharField(max_length=80, verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripcion')),
                ('disponibilidad', models.CharField(max_length=80, verbose_name='Descripcion')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
