# Generated by Django 4.0.2 on 2022-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.CharField(max_length=80, verbose_name='Disponibilidad'),
        ),
    ]
