# Generated by Django 4.0.6 on 2022-07-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_disponibilidad'),
        ('core', '0004_alter_producto_disponibilidad_perfilusuario'),
    ]

    operations = [
    ]
