# Generated by Django 4.0.5 on 2022-07-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20220712_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrBodega',
            fields=[
                ('idbodega', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idbodega')),
                ('categoria', models.CharField(max_length=20, verbose_name='categoria')),
                ('estado', models.CharField(max_length=30, verbose_name='estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
